# Generated by Django 3.2.6 on 2022-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
