# Generated by Django 3.2.6 on 2022-05-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_alter_order_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statuc',
            new_name='status',
        ),
    ]
